apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    meta.helm.sh/release-name: free5gc
    meta.helm.sh/release-namespace: free5gc
  creationTimestamp: "2025-11-24T20:42:18Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: n6network-free5gc-free5gc-upf
  namespace: free5gc
  resourceVersion: "1730610"
  uid: b51d3784-846c-4d7f-bad8-1c48d3a562e2
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "capabilities":
    { "ips": true }, "master": "ens5", "mode": "l2", "ipam": { "type": "static", "routes":
    [ { "dst": "0.0.0.0/0", "gw": "10.100.100.1" } ] } } ] }'
