apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ops-patcher
  namespace: free5gc
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","patch","update"]
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get","list","watch"]
